// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoBmqlNyqiC1CIYvwdVEGWP7-6dZzG1qU',
    appId: '1:12976450264:web:0cd916e2a309f11ccb05ad',
    messagingSenderId: '12976450264',
    projectId: 'instagram-b849d',
    authDomain: 'instagram-b849d.firebaseapp.com',
    storageBucket: 'instagram-b849d.appspot.com',
    measurementId: 'G-3PFC91PL88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeMvFSm96T_bYJbS5xlR57byNFhRAXriA',
    appId: '1:12976450264:android:68df282674295560cb05ad',
    messagingSenderId: '12976450264',
    projectId: 'instagram-b849d',
    storageBucket: 'instagram-b849d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoRmtf-m8-tI39-0brVOGyOXBABTp240c',
    appId: '1:12976450264:ios:238e94c035bb7725cb05ad',
    messagingSenderId: '12976450264',
    projectId: 'instagram-b849d',
    storageBucket: 'instagram-b849d.appspot.com',
    iosClientId: '12976450264-2vapu8cfsu85sfoaasdkeuls32162peb.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
